import AppKit.NSPasteboard
import Defaults

extension NSPasteboard.PasteboardType: @retroactive Defaults.Serializable {
    static let heic = NSPasteboard.PasteboardType(rawValue: "public.heic")
    static let jpeg = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
    static let universalClipboard = NSPasteboard.PasteboardType(rawValue: "com.apple.is-remote-clipboard")

    // See http://nspasteboard.org for more details.
    static let autoGenerated = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
    static let source = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.source")
    static let transient = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")

    static let modified = NSPasteboard.PasteboardType(rawValue: "x.nspasteboard.ModifiedType")

    /// Marks a write that came from Clipo itself so the next pasteboard change is ignored.
    static let fromClipo = NSPasteboard.PasteboardType(rawValue: "com.ymoon.clipo")

    static let microsoftObjectLink = NSPasteboard.PasteboardType(rawValue: "com.microsoft.ObjectLink")
    static let microsoftLinkSource = NSPasteboard.PasteboardType(rawValue: "com.microsoft.Link-Source")

    static let linkPresentationMetadata = NSPasteboard.PasteboardType(rawValue: "com.apple.linkpresentation.metadata")
    static let customWebKitPasteboardData = NSPasteboard.PasteboardType(rawValue: "com.apple.WebKit.custom-pasteboard-data")

    static let customChromiumWebData = NSPasteboard.PasteboardType(rawValue: "org.chromium.web-custom-data")
    static let chromiumSourceUrl = NSPasteboard.PasteboardType(rawValue: "org.chromium.source-url")
    static let chromiumSourceToken = NSPasteboard.PasteboardType(rawValue: "org.chromium.internal.source-rfh-token")

    static let notesRichText = NSPasteboard.PasteboardType(rawValue: "com.apple.notes.richtext")
}
