import AppKit
import Defaults
import Foundation

/// Polls `NSPasteboard.general` for changes and produces `ClipItem` snapshots.
/// Ported from Maccy's `Clipboard` — see `Maccy/Clipboard.swift` in
/// https://github.com/p0deje/Maccy.
@MainActor
final class ClipboardEngine {
    static let shared = ClipboardEngine()

    typealias OnNewCopyHook = (ClipItem) -> Void

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var changeCount: Int
    private var onNewCopyHooks: [OnNewCopyHook] = []

    private let dynamicTypePrefix = "dyn."
    private let microsoftSourcePrefix = "com.microsoft.ole.source."
    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    private var enabledTypes: Set<NSPasteboard.PasteboardType> { Defaults[.enabledPasteboardTypes] }
    private var disabledTypes: Set<NSPasteboard.PasteboardType> { supportedTypes.subtracting(enabledTypes) }

    private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

    init() {
        changeCount = pasteboard.changeCount
    }

    // MARK: - Lifecycle

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(
            timeInterval: Defaults[.checkInterval],
            target: self,
            selector: #selector(tick),
            userInfo: nil,
            repeats: true
        )
    }

    func restart() { start() }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHooks.append(hook)
    }

    // MARK: - Copy (write to pasteboard)

    func copy(_ item: ClipItem, removeFormatting: Bool = false) {
        pasteboard.clearContents()

        let contents = removeFormatting ? clearFormatting(item.contents) : item.contents
        let fileURLs = item.fileURLs
        let hasFileURLs = !fileURLs.isEmpty

        // Write every non-fileURL rep directly. For file items we also
        // skip the stored .string type here and re-derive it below, so
        // pasting into a text editor emits the POSIX paths rather than
        // whatever string representation (often just the filename) the
        // source app happened to put on the pasteboard.
        for content in contents {
            if content.type == NSPasteboard.PasteboardType.fileURL.rawValue { continue }
            if hasFileURLs, content.type == NSPasteboard.PasteboardType.string.rawValue { continue }
            pasteboard.setData(content.value, forType: NSPasteboard.PasteboardType(content.type))
        }

        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue,
                  let value = content.value else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.type))
            return pasteItem
        }
        if !fileURLItems.isEmpty {
            pasteboard.writeObjects(fileURLItems)
            // Synthesise a full POSIX-path string rep so pasting a file
            // item into TextEdit / VS Code / Slack yields the actual
            // "/Users/…/foo.txt" path instead of just "foo.txt".
            // Finder ignores .string when .fileURL is present, so file-
            // manager paste behaviour is unchanged.
            let paths = fileURLs.map(\.path).joined(separator: "\n")
            if !paths.isEmpty {
                pasteboard.setString(paths, forType: .string)
            }
        }

        // Mark that the next pasteboard change originated from Clipo itself.
        pasteboard.setString("", forType: .fromClipo)
        pasteboard.setString(item.sourceAppBundleID ?? "", forType: .source)

        // Sync change count immediately so we don't re-ingest our own write.
        changeCount = pasteboard.changeCount
    }

    /// Write an arbitrary text blob to the pasteboard with Clipo's own
    /// `.fromClipo` marker so the poll loop doesn't re-ingest it as a new
    /// copy event. Used by the paste-stack path which synthesises a
    /// combined payload from multiple history items.
    func writeText(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setString("", forType: .fromClipo)
        changeCount = pasteboard.changeCount
    }

    func clear() {
        guard Defaults[.clearSystemClipboard] else { return }
        pasteboard.clearContents()
    }

    // MARK: - Polling

    @objc
    private func tick() {
        checkForChangesInPasteboard()
    }

    @MainActor
    func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount

        // Skip writes coming from Clipo itself.
        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromClipo) }) == true {
            return
        }

        if Defaults[.ignoreEvents] { return }

        if shouldIgnore(Set(pasteboard.types ?? [])) { return }

        if let bundleID = sourceApp?.bundleIdentifier, shouldIgnore(bundleID) { return }

        var contents: [ClipContent] = []
        pasteboard.pasteboardItems?.forEach { item in
            var types = Set(item.types)

            if types.contains(.string) && isEmptyString(item) && !isRichText(item) { return }
            if shouldIgnore(item) { return }

            types = types
                .subtracting(disabledTypes)
                .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
                .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

            if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
                types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
            }

            for type in types {
                contents.append(ClipContent(type: type.rawValue, value: item.data(forType: type)))
            }
        }

        guard !contents.isEmpty else { return }

        // Drop monstrously large items outright. A 50 MB PDF or a giant RTF
        // blob gets the same treatment as "no text" — we never surface it.
        // Prevents SwiftData slowness and NSCache memory spikes.
        let cap = Defaults[.maxItemBytes]
        if cap > 0 {
            let totalBytes = contents.reduce(0) { $0 + ($1.value?.count ?? 0) }
            if totalBytes > cap { return }
        }

        let clip = ClipItem(contents: contents)
        clip.sourceAppBundleID = sourceApp?.bundleIdentifier
        clip.title = clip.generateTitle()

        onNewCopyHooks.forEach { $0(clip) }
    }

    // MARK: - Filtering helpers

    private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
        let extra = Defaults[.ignoredPasteboardTypes].map { NSPasteboard.PasteboardType($0) }
        let allIgnored = ignoredTypes.union(extra)
        return types.isDisjoint(with: enabledTypes) || !types.isDisjoint(with: allIgnored)
    }

    private func shouldIgnore(_ bundleID: String) -> Bool {
        if Defaults[.ignoreAllAppsExceptListed] {
            return !Defaults[.ignoredApps].contains(bundleID)
        } else {
            return Defaults[.ignoredApps].contains(bundleID)
        }
    }

    // Compiled-regex cache. Defaults observer in AppDelegate clears it when
    // the user edits the ignoreRegexp list. Without this we'd recompile
    // every user pattern on every single poll tick (0.5s).
    private var regexCache: [String: NSRegularExpression] = [:]

    func invalidateRegexCache() { regexCache.removeAll(keepingCapacity: true) }

    private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else { return false }
        let patterns = Defaults[.ignoreRegexp]
        guard !patterns.isEmpty else { return false }
        for pattern in patterns {
            let regex: NSRegularExpression?
            if let cached = regexCache[pattern] {
                regex = cached
            } else if let compiled = try? NSRegularExpression(pattern: pattern) {
                regexCache[pattern] = compiled
                regex = compiled
            } else {
                regex = nil
            }
            guard let regex else { continue }
            let range = NSRange(string.startIndex..., in: string)
            if regex.numberOfMatches(in: string, range: range) > 0 { return true }
        }
        return false
    }

    private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let s = item.string(forType: .string) else { return true }
        return s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func isRichText(_ item: NSPasteboardItem) -> Bool {
        if let data = item.data(forType: .rtf),
           let attr = NSAttributedString(rtf: data, documentAttributes: nil) {
            return !attr.string.isEmpty
        }
        if let data = item.data(forType: .html),
           let attr = NSAttributedString(html: data, documentAttributes: nil) {
            return !attr.string.isEmpty
        }
        return false
    }

    private func clearFormatting(_ contents: [ClipContent]) -> [ClipContent] {
        let strings = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }
        guard !strings.isEmpty else { return contents }
        let fileURLs = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
        return strings + fileURLs
    }
}
