import AppKit
import Defaults
import Foundation

/// Polls `NSPasteboard.general` for changes and produces `ClipItem` snapshots.
/// Ported from Maccy's `Clipboard` (see /Users/ymoon/workspace/project/swift/Maccy/Maccy/Clipboard.swift).
@MainActor
final class ClipboardEngine {
    static let shared = ClipboardEngine()

    typealias OnNewCopyHook = (ClipItem) -> Void

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var changeCount: Int
    private var onNewCopyHooks: [OnNewCopyHook] = []

    private let dynamicTypePrefix = "dyn."
    private let microsoftSourcePrefix = "com.microsoft.ole.source."
    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    private var enabledTypes: Set<NSPasteboard.PasteboardType> { Defaults[.enabledPasteboardTypes] }
    private var disabledTypes: Set<NSPasteboard.PasteboardType> { supportedTypes.subtracting(enabledTypes) }

    private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

    init() {
        changeCount = pasteboard.changeCount
    }

    // MARK: - Lifecycle

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(
            timeInterval: Defaults[.checkInterval],
            target: self,
            selector: #selector(tick),
            userInfo: nil,
            repeats: true
        )
    }

    func restart() { start() }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHooks.append(hook)
    }

    // MARK: - Copy (write to pasteboard)

    func copy(_ item: ClipItem, removeFormatting: Bool = false) {
        pasteboard.clearContents()

        let contents = removeFormatting ? clearFormatting(item.contents) : item.contents

        for content in contents {
            guard content.type != NSPasteboard.PasteboardType.fileURL.rawValue else { continue }
            pasteboard.setData(content.value, forType: NSPasteboard.PasteboardType(content.type))
        }

        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue,
                  let value = content.value else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.type))
            return pasteItem
        }
        if !fileURLItems.isEmpty {
            pasteboard.writeObjects(fileURLItems)
        }

        // Mark that the next pasteboard change originated from Clipo itself.
        pasteboard.setString("", forType: .fromClipo)
        pasteboard.setString(item.sourceAppBundleID ?? "", forType: .source)

        // Sync change count immediately so we don't re-ingest our own write.
        changeCount = pasteboard.changeCount
    }

    func clear() {
        guard Defaults[.clearSystemClipboard] else { return }
        pasteboard.clearContents()
    }

    // MARK: - Polling

    @objc
    private func tick() {
        checkForChangesInPasteboard()
    }

    @MainActor
    func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount

        // Skip writes coming from Clipo itself.
        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromClipo) }) == true {
            return
        }

        if Defaults[.ignoreEvents] { return }

        if shouldIgnore(Set(pasteboard.types ?? [])) { return }

        if let bundleID = sourceApp?.bundleIdentifier, shouldIgnore(bundleID) { return }

        var contents: [ClipContent] = []
        pasteboard.pasteboardItems?.forEach { item in
            var types = Set(item.types)

            if types.contains(.string) && isEmptyString(item) && !isRichText(item) { return }
            if shouldIgnore(item) { return }

            types = types
                .subtracting(disabledTypes)
                .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
                .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

            if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
                types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
            }

            for type in types {
                contents.append(ClipContent(type: type.rawValue, value: item.data(forType: type)))
            }
        }

        guard !contents.isEmpty else { return }

        let clip = ClipItem(contents: contents)
        clip.sourceAppBundleID = sourceApp?.bundleIdentifier
        clip.title = clip.generateTitle()

        onNewCopyHooks.forEach { $0(clip) }
    }

    // MARK: - Filtering helpers

    private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
        let extra = Defaults[.ignoredPasteboardTypes].map { NSPasteboard.PasteboardType($0) }
        let allIgnored = ignoredTypes.union(extra)
        return types.isDisjoint(with: enabledTypes) || !types.isDisjoint(with: allIgnored)
    }

    private func shouldIgnore(_ bundleID: String) -> Bool {
        if Defaults[.ignoreAllAppsExceptListed] {
            return !Defaults[.ignoredApps].contains(bundleID)
        } else {
            return Defaults[.ignoredApps].contains(bundleID)
        }
    }

    private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else { return false }
        for pattern in Defaults[.ignoreRegexp] {
            if let regex = try? NSRegularExpression(pattern: pattern) {
                let range = NSRange(string.startIndex..., in: string)
                if regex.numberOfMatches(in: string, range: range) > 0 { return true }
            }
        }
        return false
    }

    private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let s = item.string(forType: .string) else { return true }
        return s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func isRichText(_ item: NSPasteboardItem) -> Bool {
        if let data = item.data(forType: .rtf),
           let attr = NSAttributedString(rtf: data, documentAttributes: nil) {
            return !attr.string.isEmpty
        }
        if let data = item.data(forType: .html),
           let attr = NSAttributedString(html: data, documentAttributes: nil) {
            return !attr.string.isEmpty
        }
        return false
    }

    private func clearFormatting(_ contents: [ClipContent]) -> [ClipContent] {
        let strings = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }
        guard !strings.isEmpty else { return contents }
        let fileURLs = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
        return strings + fileURLs
    }
}
