import AppKit
import Defaults
import Foundation

enum SearchMode: String, Defaults.Serializable, CaseIterable, Identifiable {
    case exact, contains, fuzzy
    var id: String { rawValue }
    var label: String {
        switch self {
        case .exact:    return "Exact"
        case .contains: return "Contains"
        case .fuzzy:    return "Fuzzy"
        }
    }
}

enum SortMode: String, Defaults.Serializable, CaseIterable, Identifiable {
    case lastCopiedAt, firstCopiedAt, numberOfCopies
    var id: String { rawValue }
    var label: String {
        switch self {
        case .lastCopiedAt:   return "Last Copied"
        case .firstCopiedAt:  return "First Copied"
        case .numberOfCopies: return "Most Used"
        }
    }
}

enum MenuBarIcon: String, Defaults.Serializable, CaseIterable, Identifiable {
    case clipboard = "doc.on.clipboard"
    case tray = "tray.full"
    case simple = "clipboard"
    var id: String { rawValue }
    var label: String {
        switch self {
        case .clipboard: return "Clipboard"
        case .tray:      return "Tray"
        case .simple:    return "Simple"
        }
    }
}

extension Defaults.Keys {
    // Clipboard engine
    static let checkInterval = Key<TimeInterval>("checkInterval", default: 0.5)
    static let maxHistorySize = Key<Int>("maxHistorySize", default: 500)
    /// Per-item byte ceiling. Anything whose total content bytes exceed this
    /// is silently dropped instead of being ingested. Protects SwiftData +
    /// NSCache from a 50 MB-PDF paste freezing the app. Default 20 MB.
    static let maxItemBytes = Key<Int>("maxItemBytes", default: 20 * 1024 * 1024)

    // OCR — run on-device text recognition against newly-copied images so
    // the words visible in them become searchable. Default on.
    static let ocrEnabled = Key<Bool>("ocrEnabled", default: true)
    /// Pixel-count cap for OCR candidates. Images over this are skipped so
    /// a massive screenshot doesn't hold an OCR job slot for seconds.
    /// Hidden default — power users can tweak via `defaults write`.
    static let ocrMaxPixels = Key<Int>("ocrMaxPixels", default: 10_000_000)
    static let enabledPasteboardTypes = Key<Set<NSPasteboard.PasteboardType>>(
        "enabledPasteboardTypes",
        default: [.fileURL, .html, .png, .rtf, .string, .tiff]
    )
    /// Pasteboard-type markers that indicate "don't archive this copy".
    /// Beyond the three nspasteboard.org standards (`autoGenerated`,
    /// `concealed`, `transient`) that are hard-coded in `ClipboardEngine`,
    /// this set lists app-specific types advertised by common password
    /// managers / text expanders so a fresh install already skips their
    /// output without the user having to configure anything.
    ///
    /// Matches Maccy's defaults (battle-tested over many years):
    /// - 1Password ("com.agilebits.onepassword")
    /// - KeeWeb ("net.antelle.keeweb")
    /// - TypeIt4Me ("com.typeit4me.clipping")
    /// - Peter Maurer's transient marker ("de.petermaurer.TransientPasteboardType")
    /// - Generic "pasteboard generator type" tag
    ///
    /// Bitwarden, LastPass, Dashlane, Enpass, and Apple's Passwords app
    /// rely on the standard `.concealed` flag and so are already covered
    /// by the hard-coded set in ClipboardEngine — no entry needed here.
    static let ignoredPasteboardTypes = Key<Set<String>>(
        "ignoredPasteboardTypes",
        default: [
            "Pasteboard generator type",
            "com.agilebits.onepassword",
            "com.typeit4me.clipping",
            "de.petermaurer.TransientPasteboardType",
            "net.antelle.keeweb",
        ]
    )
    /// Source apps whose copies are never archived. Pre-populated with
    /// Apple's first-party password tooling — bundle-ID-based filtering is
    /// more reliable here than hoping they advertise `.concealed` for every
    /// copy path (e.g. "Copy Username" vs "Copy Password" may not both be
    /// flagged). Users can add/remove apps in Settings → Ignore → Apps.
    static let ignoredApps = Key<[String]>(
        "ignoredApps",
        default: [
            "com.apple.Passwords",       // macOS 15+ Passwords.app
            "com.apple.keychainaccess",  // Legacy Keychain Access
        ]
    )
    static let ignoreAllAppsExceptListed = Key<Bool>("ignoreAllAppsExceptListed", default: false)
    static let ignoreRegexp = Key<[String]>("ignoreRegexp", default: [])
    static let ignoreEvents = Key<Bool>("ignoreEvents", default: false)

    // UI - layout
    static let panelHeight = Key<Double>("panelHeight", default: 330)
    static let panelBottomInset = Key<Double>("panelBottomInset", default: 0)

    // UI - appearance (new)
    static let menuBarIcon = Key<MenuBarIcon>("menuBarIcon", default: .clipboard)
    static let accentColorHex = Key<String>("accentColorHex", default: "#FF6A3D")
    static let showSourceIcon = Key<Bool>("showSourceIcon", default: true)
    static let showFooterHints = Key<Bool>("showFooterHints", default: true)

    // Behavior (new)
    static let searchMode = Key<SearchMode>("searchMode", default: .contains)
    static let sortBy = Key<SortMode>("sortBy", default: .lastCopiedAt)

    // Paste behavior
    static let pasteByDefault = Key<Bool>("pasteByDefault", default: true)
    static let removeFormattingByDefault = Key<Bool>("removeFormattingByDefault", default: true)
    static let clearSystemClipboard = Key<Bool>("clearSystemClipboard", default: false)
    static let clearOnQuit = Key<Bool>("clearOnQuit", default: false)

    // Scripts — IDs that are disabled (unchecked in Settings).
    static let disabledScriptIDs = Key<Set<String>>("disabledScriptIDs", default: [])

    // One-time seeding — true after the default "Important" pinboard has been created.
    static let didInstallDefaultPinboards = Key<Bool>("didInstallDefaultPinboards", default: false)
    /// Set true after the welcome window has been dismissed so first-launch
    /// onboarding runs exactly once per install.
    static let didShowOnboarding = Key<Bool>("didShowOnboarding", default: false)
}
